name: Build and Deploy to App Service

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Solution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Set up .NET Core
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: '8.x'
      #     include-prerelease: true

      # - name: Build with dotnet
      #   run: dotnet build --configuration Release

      # - name: dotnet publish
      #   run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      # - name: Upload artifact for deployment job
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: .net-app
      #     path: ${{env.DOTNET_ROOT}}/myapp
      - name: Build and Push Image
        run: |
          az acr login --name registryxavi --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }} &&
          docker build -t registryxavi.azurecr.io/xavi:${{ github.sha }} -f dockerfile . &&
          docker push registryxavi.azurecr.io/xavi:${{ github.sha }}

      # - name: ACR build
      #   id: acr
      #   uses: azure/acr-build@v1
      #   with:
      #     service_principal: ${{ secrets.service_principal }}
      #     service_principal_password: ${{ secrets.service_principal_password }}
      #     tenant: ${{ secrets.tenant }}
      #     registry: ${{ secrets.registry }}
      #     repository: ${{ secrets.repository }}
      #     image: xavi-microhack
      #     git_access_token: ${{ secrets.git_access_token }}
      #     folder: .
      #     dockerfile: ../../dockerfile
      #     branch: main
      #     build_args: '[{"arg_one":"value_one"}, {"arg_two":"value_two"}]'


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: ${{ secrets.ACR_USERNAME }}
          containerAppName: managedEnvironment-user7-9db8
          resourceGroup: user7
          imageToDeploy: registryxavi.azurecr.io/xavi:${{ github.sha }}
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2

  #     - name: Login to Azure Container Registry
  #       run: |
  #         az acr login --name registryxavi --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}

  #     - name: Deploy to Azure Web App
  #       uses: azure/webapps-container-deploy@v1
  #       with:
  #         app-name: 'microhack-webapp'
  #         slot-name: 'Production'
  #         images: 'registryxavi.azurecr.io/xavi:${{ github.sha }}'
  #         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C48CC2577AB24EFF9C988AEAE5BE1436 }}
  # deploy:
  #   name: Deploy Solution
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: .net-app

  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'microhack-webapp'
  #         slot-name: 'Production'
  #         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C48CC2577AB24EFF9C988AEAE5BE1436 }}
  #         package: .
